"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ╭─](bg:color_fg0 fg:color_blue)\
[](bg:color_blue fg:color_blue)\
$username\
[](bg:color_fg0 fg:color_blue)\
[](bg:color_lavender fg:color_fg0)\
$cmd_duration\
[](bg:color_fg0 fg:color_lavender)\
[](bg:color_yellow fg:color_fg0)\
$directory\
[](bg:color_fg0 fg:color_yellow)\
[](bg:color_aqua fg:color_fg0)\
$git_branch\
$git_status\
[](bg:color_fg0 fg:color_aqua)\
[](bg:color_sapphire fg:color_fg0)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$haxe\
$hg_branch\
$hostname\
$julia\
$lua\
$nim\
$crystal\
$dart\
$deno\
$elixir\
$elm\
$fennel\
$fortran\
$fossil_branch\
$gcloud\
$pixi\
$kotlin\
$haskell\
$ruby\
$python\
[](bg:color_fg0 fg:color_sapphire)\
$docker_context\
$conda\
$pixi\
$line_break\
$character"""

palette = 'gruvbox_air'

[palettes.gruvbox_air]
color_fg0 = '#000000'
color_bg1 = '#000000'
color_bg3 = '#000000'
color_blue = '#0000ff'
color_aqua = '#00ff00'
color_green = '#00ff00'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#ffff00'
color_white = '#ffffff'
color_sapphire = '#1E66F5'
color_lavender = '#B4BEFE'

[os]
disabled = false
style = "bg:color_red fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_blue fg:color_fg0"
style_root = "bg:color_red fg:color_white"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Videos" = " "
"Developer" = "󰲋 "
"CSEC" = "󰈸"
"PDFS" = " "
"VIDEOS" = ""
"put-it" = "◈"
"rev-eng" = "◄"
"cm-lang" = " "
"m-codes" = " "
"ARENA" = "󰈸"

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = "x"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[ruby]
symbol = ""
style = "bg:color_red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[haskell]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[haxe]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[hg_branch]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[hostname]
ssh_symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[julia]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[lua]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[crystal]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[dart]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[deno]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[elixir]
symbol = " "
style = "bg:color_red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[elm]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[fennel]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[fortran]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[fossil_branch]
symbol = " "
style = "bg:color_yellow"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[gcloud]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sapphire)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[pixi]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

# [time]
# disabled = false
# time_format = "%R"
# style = "bg:color_bg1"
# format = '[[ $time ](fg:color_white  bg:color_blue)]($style)'

[cmd_duration]
format = '[[ $duration ](fg:color_bg1  bg:color_lavender)]($style)'
min_time = 1

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ╰─❯](bold fg:color_blue)'
error_symbol = '[ ╰─🚫](bold fg:color_blue)'
